from panda3d.core import *

cfg = {}


def loadcfg():
    cfg['srgb'] = ConfigVariableBool('framebuffer-srgb', False).getValue()
    cfg['filters'] = ConfigVariableInt('koparka-filters', 2).getValue()
    # render grass? 0=no 1=yes
    cfg['grass'] = ConfigVariableBool('koparka-use-grass', True).getValue()
    # size of the maps savesd by the editor
    cfg['h_map_size'] = ConfigVariableInt('koparka-height-map-size', 512).getValue()
    cfg['a_map_size'] = ConfigVariableInt('koparka-attribute-map-size', 512).getValue()
    cfg['g_map_size'] = ConfigVariableInt('koparka-grass-map-size', 512).getValue()
    cfg['w_map_size'] = ConfigVariableInt('koparka-walk-map-size', 256).getValue()
    # where to load the data from
    cfg['brush_dir'] = ConfigVariableString('koparka-brush-dir', "brush/").getValue()
    cfg['dif_tex_dir'] = ConfigVariableString('koparka-terrain-tex-diffuse-dir', "tex/diffuse/").getValue()
    cfg['nrm_tex_dir'] = ConfigVariableString('koparka-terrain-tex-normal-dir', "tex/normal/").getValue()
    cfg['grs_tex_dir'] = ConfigVariableString('koparka-grass-tex-dir', "grass/").getValue()
    cfg['model_dir'] = ConfigVariableString('koparka-model-dir', "models/").getValue()
    cfg['walls_dir'] = ConfigVariableString('koparka-walls-dir', "models_walls/").getValue()
    cfg['actors_dir'] = ConfigVariableString('koparka-actors-dir', "models_actor/").getValue()
    cfg['coll_dir'] = ConfigVariableString('koparka-collision-dir', "models_collision/").getValue()
    # default data
    cfg['h_map_def'] = ConfigVariableString('koparka-default-height-map', "data/def_height.png").getValue()
    cfg['a_map_def'] = ConfigVariableString('koparka-default-attribute-map', "data/atr_def.png").getValue()
    cfg['terrain_mesh'] = ConfigVariableString('koparka-default-terrain-mesh', "data/mesh80k.bam").getValue()
    cfg['sky_mesh'] = ConfigVariableString('koparka-default-skydome-mesh', "data/skydome2").getValue()
    cfg['sky_tex'] = ConfigVariableString('koparka-default-sky-tex', "data/clouds.png").getValue()
    cfg['sky_color'] = ConfigVariableString('koparka-default-sky-color-tex', "data/sky_grad.png").getValue()
    cfg['water_mesh'] = ConfigVariableString('koparka-default-water-mesh', "data/waterplane").getValue()
    cfg['water_tex'] = ConfigVariableString('koparka-default-water-tex', "data/water.png").getValue()
    cfg['wave_tex'] = ConfigVariableString('koparka-default-water-wave-tex', "data/ocen3.png").getValue()
    # shadows (what is seen by the shadow casting camera)
    cfg['shadow_terrain'] = ConfigVariableBool('koparka-terrain-shadows', True).getValue()
    cfg['shadow_grass'] = ConfigVariableBool('koparka-grass-shadows', False).getValue()
    cfg['shadow_objects'] = ConfigVariableBool('koparka-object-shadows', True).getValue()
    # water reflections (what is seen by the water reflection camera)
    cfg['reflect_terrain'] = ConfigVariableBool('koparka-terrain-reflection', True).getValue()
    cfg['reflect_objects'] = ConfigVariableBool('koparka-objects-reflection', True).getValue()
    cfg['reflect_sky'] = ConfigVariableBool('koparka-sky-reflection', True).getValue()
    cfg['reflect_grass'] = ConfigVariableBool('koparka-grass-reflection', False).getValue()
    # shaders
    cfg['shader_terrain_v'] = ConfigVariableString('koparka-shader-terrain_v', 'shaders/terrain_v.glsl').getValue()
    cfg['shader_terrain_f'] = ConfigVariableString('koparka-shader-terrain_f', 'shaders/terrain_f.glsl').getValue()
    cfg['shader_terrain_tc'] = ConfigVariableString('koparka-shader-terrain_tc', '').getValue()
    cfg['shader_terrain_tes'] = ConfigVariableString('koparka-shader-terrain_tes', '').getValue()
    cfg['shader_terrain_geo'] = ConfigVariableString('koparka-shader-terrain_geo', '').getValue()
    cfg['shader_terrain_w_v'] = ConfigVariableString('koparka-shader-terrain_w_v',
                                                     'shaders/terrain_v.glsl').getValue()
    cfg['shader_terrain_w_f'] = ConfigVariableString('koparka-shader-terrain_w_f',
                                                     'shaders/terrain_w_f.glsl').getValue()
    cfg['shader_editor_v'] = ConfigVariableString('koparka-shader-editor_v', 'shaders/editor_v.glsl').getValue()
    cfg['shader_editor_f'] = ConfigVariableString('koparka-shader-editor_f', 'shaders/editor_f.glsl').getValue()
    cfg['shader_water_v'] = ConfigVariableString('koparka-shader-water_v', 'shaders/water2_v.glsl').getValue()
    cfg['shader_water_f'] = ConfigVariableString('koparka-shader-water_f', 'shaders/water2_f.glsl').getValue()
    cfg['shader_grass_v'] = ConfigVariableString('koparka-shader-grass_v', 'shaders/grass_lights_v.glsl').getValue()
    cfg['shader_grass_f'] = ConfigVariableString('koparka-shader-grass_f', 'shaders/grass_lights_f.glsl').getValue()
    cfg['shader_sky_v'] = ConfigVariableString('koparka-shader-sky_v', 'shaders/cloud_v.glsl').getValue()
    cfg['shader_sky_f'] = ConfigVariableString('koparka-shader-sky_f', 'shaders/cloud_f.glsl').getValue()
    # keymap
    cfg['key_paint'] = ConfigVariableString('koparka-key-paint', 'mouse1').getValue()
    cfg['key_right'] = ConfigVariableString('koparka-key-rotate-r', 'e').getValue()
    cfg['key_left'] = ConfigVariableString('koparka-key-rotate-l', 'q').getValue()
    cfg['key_scale_up'] = ConfigVariableString('koparka-key-scale-up', 'd').getValue()
    cfg['key_scale_down'] = ConfigVariableString('koparka-key-scale-down', 'a').getValue()
    cfg['key_alpha_up'] = ConfigVariableString('koparka-key-alpha-up', 'w').getValue()
    cfg['key_alpha_down'] = ConfigVariableString('koparka-key-alpha-down', 's').getValue()
    cfg['key_next'] = ConfigVariableString('koparka-key-next', 'tab').getValue()
    cfg['key_prev'] = ConfigVariableString('koparka-key-prev', 'backspace').getValue()
    cfg['key_mode_height'] = ConfigVariableString('koparka-key-height-mode', 'f1').getValue()
    cfg['key_mode_tex'] = ConfigVariableString('koparka-key-texture-mode', 'f2').getValue()
    cfg['key_mode_grass'] = ConfigVariableString('koparka-key-grass-mode', 'f3').getValue()
    cfg['key_mode_obj'] = ConfigVariableString('koparka-key-object-mode', 'f4').getValue()
    cfg['key_mode_walk'] = ConfigVariableString('koparka-key-walk-mode', 'f5').getValue()
    cfg['key_config'] = ConfigVariableString('koparka-key-config', 'f6').getValue()
    cfg['key_save'] = ConfigVariableString('koparka-key-save', 'f7').getValue()
    cfg['key_h'] = ConfigVariableString('koparka-key-axis-h', '1').getValue()
    cfg['key_p'] = ConfigVariableString('koparka-key-axis-p', '2').getValue()
    cfg['key_r'] = ConfigVariableString('koparka-key-axis-r', '3').getValue()
    cfg['key_cam_rotate'] = ConfigVariableString('koparka-key-camera-rotate', 'mouse2').getValue()
    cfg['key_cam_pan'] = ConfigVariableString('koparka-key-camera-pan', 'mouse3').getValue()
    cfg['key_cam_zoomin'] = ConfigVariableString('koparka-key-camera-zoomin', 'wheel_up').getValue()
    cfg['key_cam_zoomout'] = ConfigVariableString('koparka-key-camera-zoomout', 'wheel_down').getValue()
    cfg['key_cam_slow'] = ConfigVariableString('koparka-key-camera-slow', 'alt').getValue()
    cfg['key_cam_fast'] = ConfigVariableString('koparka-key-camera-fast', 'control').getValue()
    cfg['key_cam_rotate2'] = ConfigVariableString('koparka-key-camera-rotate2', 'control').getValue()
    cfg['key_cam_pan2'] = ConfigVariableString('koparka-key-camera-pan2', 'alt').getValue()
    cfg['key_cam_zoomin2'] = ConfigVariableString('koparka-key-camera-zoomin2', '=').getValue()
    cfg['key_cam_zoomout2'] = ConfigVariableString('koparka-key-camera-zoomout2', '-').getValue()
    cfg['theme'] = ConfigVariableString('koparka-gui-theme', 'icon').getValue()
    cfg['use_gl_select'] = ConfigVariableBool('koparka-gl-select', False).getValue()
